### ISSUE TITLE
Node Type (xray) Protocol (vmess ) Not Import in Client app

### ISSUE THREAD

**Issue by r0zbeh** [trojanpanel/install-script#89] opened 2022-12-24 10:23 UTC
When i create xray node (vless and trojan ) every things is good and this protocol easy imported to (NapsternetV and V2rayN) but when i cereate Vmess Protocol it will be create but i cant import it in any client !  error (Invalid V2ray configs ) is appear !!!

I need this protocol for Whatsapp Voice call because vless and trojan dont support Udp to Tcp and whtasapp use Udp for voice call !

please if someone know about fix this problem tell me !!

**Comment by gladiators1980** [comment] 2022-12-25 17:50
I check it and i think if your android version is 8 or above not problem in its work ok but in android 7 and lower not import no clash link no node link work

**Comment by r0zbeh** [comment] 2022-12-25 21:27
I test in windows and Ios and same result !

**Comment by gladiators1980** [comment] 2022-12-26 11:38
in ios with shadorocket no problem and in windows with clash version 20.8 i don't have any problem

**Comment by KRU3L** [comment] 2022-12-26 13:16
> When i create xray node (vless and trojan ) every things is good and this protocol easy imported to (NapsternetV and V2rayN) but when i cereate Vmess Protocol it will be create but i cant import it in any client ! error (Invalid V2ray configs ) is appear !!!

> please if someone know about fix this problem tell me !!

if I understood your situation, the problem is for Vmess syntax.
when you copy Vmess Config from Panel the Syntax is like this:
`vmess://UUID@HOST:PORT?type=tcp&security=none&alterId=0#REMARK`
which is exactly the same as Trojan & Trojan-Go configs!
but the acceptable syntax for many clients is:
`vmess://base64encoded-config`
the quick fix for this matter is to copy UUID and host manually to the client app and share it from there.

**Closed** 2022-12-27 07:13 UTC
